---
title: "Cleaning individual
 data with biologically implausible values in NCD-RisC database"
#author: "NCD RisC"
#date: "19/01/2022"
output: md_document
bibliography: biblio.bib
link-citations: yes
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/cardiff-university-vancouver.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Criteria and procedure for data cleaning in the NCD-RisC database

This document is the protocol for cleaning multiple variables in the NCD-RisC database, which has the following steps: \

  1.	Applying univariate cleaning criteria\
  2.	Applying multivariate cleaning criteria\
  3.	Multivariate outlier detection\

### 1.	Univariate plausibility ranges

Data outside the following plausibility ranges are removed.

*Anthropometrics*


|Variable   | Height (cm)| Weight (kg)| BMI (kg/m2) | Waist (cm) | Hip (cm) | Waist-to-hip ratio| Waist-to-height ratio|
|:----------|:-----------|:-----------|:------------|:-----------|:---------|:------------------|:---------------------|
|5-9 years  |   60-180   |    5-90    |     6-40    |   20-150   |  30-180  |       0.4-1.8     |          0.2-1.5     |          
|10-14 years|   80-200   |    8-150   |     8-60    |   20-200   |  30-200  |       0.4-1.8     |          0.2-1.5     |                 
|15+ years  |   100-250  |   12-300   |     10-80   |   30-300   |  40-300  |       0.4-2.0     |          0.2-2.0     |

\n

*Blood Pressure*

|Variable   | SBP (mmHg) |DBP (mmHg)|
|:----------|:-----------|:---------|
|All ages   |   70-270   |  30-150  |

\n

*Lipids*

|Variable   | TC (mmol/L) |LDL (mmol/L)|HDL (mmol/L)|Triglycerides (mmol/L)|
|:----------|:------------|:-----------|:-----------|:---------------------|
|All ages   |   1.75-20   |  0.5-10    |  0.4-5     |  0.2-20              |

\n

*Glucose*

|Variable   | FPG (mmol/L)|OGTT (mmol/L)|HbA1c (%)|
|:----------|:------------|:------------|:--------|
|All ages   |   2-30      |  2-30       |  3-18   |

\n

*Kidney function related variable*

|Variable   | Serum creatinine (µmol/L)|eGFR (mL/min/1.73m2)|
|:----------|:-------------------------|:-------------------|
|All ages   |   8-1800                 |  5-250             |
eGFR: estimated glomerular filtration rate
\n

### 2. Multivariate constraints

    
The following constraints are applied after removing data outside the plausibility ranges listed above:\

  -	SBP > DBP\
If multiple measurements of blood pressure are taken, the average SBP and DBP are calculated by discarding the first measurement and averaging the remainders. The averaging should be done after excluding measurements outside of univariate plausibility ranges noted in the first section and before applying multivariate constraints or multivariate outlier detection
  -	TC > LDL\
  -	TC > HDL\
  - TC – (LDL + HDL) $\leq$ margin of error*

\n
   
*“margin of error” is determined by using the Cholesterol Reference Method Laboratory Network permitted measurement error limits for TC (8.9%), HDL (13%) and LDL (12%) as follows:\

-	Calculate errors in worst case scenario, i.e., TC underestimated and HDL/LDL overestimated, each by the largest error permitted;\
-	The limit of errors by quartiles of TC using US NHANES data: \


|TC range (mmol/L)       | <4.040 |4.040 to <4.714|4.714 to <5.465| $\geq$ 5.465|
|:-----------------------|:-------|:--------------|:--------------|:--------|
|Margin of error (mmol/L)|-0.7125 | -0.8821       | -0.9700       | -1.7520 |

### 3. Multivariate outlier detection

After applying both univariate plausibility ranges and multivariate constraints, multivariate outlier detection is carried out on pairs of variables within the same risk factor family (see lists later).\
In each pair, a method based on Mahalanobis distance @filzmoser2004multivariate is used to calculate the distance of the data points to the centre of all available data, and those that lie outside a certain threshold will be removed. Although called “outlier detection”, the threshold is chosen to catch only extreme values that are implausible. The points detected and removed should be examined in scatter plots.


#### Data Normalization 

Mahalanobis outlier detection method assumes the data to be normally distributed. 
We suggest to compare the distribution of each variable to the variable log transformed, and pick the closest to normal distribution. 
In case neither the variable nor it's log transformation are close to be normally distributed, alternative non-parametric methods should be used. 


#### Pairs of variables considered

All pairs of variables of interest from the same risk factor family are examined (see lists in the first section of this document). Exceptions are noted below.

-Some variables, e.g., FPG, OGTT, LDL and non-HDL cholesterol, are very skewed even after log-transformation, therefore we do not recommend cleaning any pair that includes any of them using the method based on Mahalanobis distance. Alternative outlier detection methods are currently being explored for NCD-RisC work.\
-For anthropometrics variables, the procedure should be applied separately for children (5-9 years), adolescents (10-14 years), and adults (15+ years).\
-eGFR is calculated from serum creatinine using a regression-based model (eg. CKD-EPI) hence multivariate cleaning is not needed.\


#### Procedure of multivariate outlier detection

For all pairs that multivariate cleaning are applied to, the cleaning process is to:\
  -	Compute the Mahalanobis of distance of all the data points after normalisation\
  -	Exclude points with distance larger than 68.5  (quantile of chi2 distribution equivalent to 8SD for normal distribution)\


#### Code and example 
For the code and an example on simulated data of the multivariate outlier detection procedure go to:
https://github.com/NCD-RisC/Multivariate-cleaning

**References:**


  